=== valentindoulcier/rba-innophyt/Site/arbres/arbre.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT arbre (branche)>

<!ELEMENT branche (question)>
<!ATTLIST branche id ID #REQUIRED>
<!ATTLIST branche type CDATA #IMPLIED>
<!ATTLIST branche date CDATA #IMPLIED>

<!ELEMENT question (reponse+, media*)>
<!ATTLIST question id ID #REQUIRED>
<!ATTLIST question texte CDATA #REQUIRED>

<!ELEMENT reponse ((branche|resultat), media*)>
<!ATTLIST reponse id ID #REQUIRED>
<!ATTLIST reponse texte CDATA #REQUIRED>

<!ELEMENT resultat (nom, type, regimeAlimentaire, informations, media*)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT regimeAlimentaire (#PCDATA)>
<!ELEMENT informations (#PCDATA)>
<!ATTLIST resultat id ID #REQUIRED>

<!ELEMENT media ((img?, sound?, video?)+, legende+)>
<!ELEMENT img EMPTY>
<!ATTLIST img id ID #REQUIRED>
<!ATTLIST img src CDATA #REQUIRED>
<!ELEMENT sound EMPTY>
<!ATTLIST sound id ID #REQUIRED>
<!ATTLIST sound src CDATA #REQUIRED>
<!ELEMENT video EMPTY>
<!ATTLIST video id ID #REQUIRED>
<!ATTLIST video src CDATA #REQUIRED>
<!ELEMENT legende (#PCDATA)>

=== valentindoulcier/rba-innophyt/Site/structure_xml.xml
<?xml version = '1.0' encoding="UTF8"?> 
<!DOCTYPE arbre SYSTEM "arbre.dtd">

<arbre>
	<branche id="b1" type="Accueil" date="jj/mm/yyy">
		<question id="q1" texte="Que voyez vous ?">
			<reponse id="r1" texte="6 pattes">
				<branche id="b2">
					<question id="q21" texte="Quelle est la taille de l'arachnide ?">
						<reponse id="r21" texte="Foobar" >
							<resultat id="res21">
								<nom>Nom de la morpho-espèce trouvée</nom>
								<type>MEL1</type>
								<regimeAlimentaire>Prédateur</regimeAlimentaire>
								<informations>Informations complementaires sur la morpho-espèce</informations>
								<media>
									<img id="img72" src="medias/Reponse2/1_.jpg" />
									<legende>Mais lol</legende>
								</media>
								<media>
									<img id="img26" src="medias/Reponse3/1.jpg" />
									<legende>Mais lol</legende>
								</media>
							</resultat>	
							<media>
								<img id="img77" src="medias/Reponse3/1.jpg" />
								<legende>C'est toto avec 6 pattes</legende>
							</media>							
						</reponse>	
						<media>
							<video id="img87" src="medias/epicsax.flv" />
							<legende>Epic sax ?</legende>
						</media>				
					</question>
				</branche>
				<media>
					<img id="img11" src="medias/Reponse1/1.jpg" />
					<legende>Une libelule</legende>
				</media>			
				<media>
					<img id="img12" src="medias/Reponse1/1_.jpg" />
					<legende>Foobar</legende>
				</media>	
			</reponse>
			<reponse id="r2" texte="8 pattes, ailes et antennes absentes">
				<branche id="b3" type="Arachnide">
					<question id="q2" texte="Quelle est la taille de l'arachnide ?">
						<reponse id="r3" texte="Supérieur à 5 mm" >
							<resultat id="res1">
								<nom>Nom de la morpho-espèce trouvée</nom>
								<type>MEL1</type>
								<regimeAlimentaire>Prédateur</regimeAlimentaire>
								<informations>Informations complementaires sur la morpho-espèce</informations>
								<media>
									<img id="img724" src="medias/Reponse2/1_.jpg" />
									<legende>Image 1</legende>
								</media>
								<media>
									<img id="img262" src="medias/Reponse3/1.jpg" />
									<legende>Image 2</legende>
								</media>								
							</resultat>
							<media>
								<img id="img2" src="medias/Reponse2/1_.jpg" />
								<legende>Mais lol</legende>
							</media>						
						</reponse>
						<reponse id="r41" texte="Inférieur à 5 mm">
							<resultat id="res41">
								<nom>Nom de la morpho-espèce trouvée</nom>
								<type>MEL1</type>
								<regimeAlimentaire>Prédateur</regimeAlimentaire>
								<informations>Informations complementaires sur la morpho-espèce</informations>							
							</resultat>	
							<media>
								<img id="img57" src="medias/Reponse3/1.jpg" />
								<legende>C'est toto avec 6 pattes</legende>
							</media>						
						</reponse>
					</question>
				</branche>
				<media>
					<video id="vid41" src="medias/video.flv" />
					<legende>Rick rolled!</legende>
				</media>
				<media>
					<sound id="snd41" src="medias/Britney Spears - Toxic.mp3" />
					<legende>Britney Spears</legende>
				</media>			
			</reponse>
			<media>
				<img id="img61" src="medias/Reponse2/1.jpg" />
				<legende>Vous devez nous dire ce que vous avez vue !!!</legende>
			</media>
		</question>
	</branche>
</arbre>
